### PR TITLE
Checklist implementation

### PR DESCRIPTION
**Pull request by savage13**
Orignal version was closed as I made a mess of the history.

---

Added a checklist functionality
- Uses the Tasks pane: `spane-dummy`
- Markers
   - Copies and modifies image icons by adding a shadowUrl for the check mark / badge
      - For `MapGenericLocationMarker`
   - For other markers derived `MapMarkerCanvasImpl` (only Koroks and Location Names)
      - Modifies `_updatePath` to draw the check mark / badge
      - Required expanding the region defined by `_updateBounds` to include the badge
- Checklists
   - Lists are stored in `Settings` under `checklists`.  Each checklist has a `name`, `query` and the `items` in the list (hash_id, name, ui_name, map_name, pos).
   - Marked values are stored directly under checklists by the object's `hash_id`.
- Context menu
   - Items have an new context menu (`Toggle Completed`)
 
Not sure about:
- Storing checklist in the Settings (localStorage)
   - Checklist item storage seems large; would it be better to populate the list when needed (using a query) instead of storing all the items. The checklist does not store if an item is marked.
- Modifying the Korok markers within `_updatePath`
- Impacts on responsiveness; while developing it does not appear to lag

- - -
This change is [Reviewable](https://reviewable.io/reviews/zeldamods/objmap-totk/70)

### CODE REVIEW

**Comment by leoetlino** [comment]
Haven't looked at the code, just some high level comments:

> Uses the Tasks pane: spane-dummy

If you re-added the Tasks pane, its ID shouldn't be spane-dummy.

> Markers

I think it might be better to just hide the marker entirely? Makes it easier to see which map points are left. (Though if we hide completed points there should be an option to show all completed points so that users can undo their mistakes.)

> Storing checklist in the Settings (localStorage)
> * Checklist item storage seems large; would it be better to populate the list when needed (using a query) instead of storing all the items. The checklist does not store if an item is marked.

Most browsers seem to have a 5MB size limit for localStorage, so we should avoid storing large amounts of data (especially when drawn markers are also in localStorage).

I would suggest looking into IndexedDB as that has a much higher size limit and checklist data is easy to store in a DB. Browser support seems decent: https://caniuse.com/indexeddb

**Comment by leoetlino** [comment]
> Lists are stored in Settings under checklists. Each checklist has a name, query and the items in the list (hash_id, name, ui_name, map_name, pos).

Do we actually need to store ui_name? I think we can just derive that from the name.

Also, we should store map_type + map_name.

**Comment by savage13** [comment]
indexeddb looks good to me. Will write an updated version.

**Comment by savage13** [comment]
This adds IndexedDB using the library [idb](https://www.npmjs.com/package/idb)
`src/util/Checklist.ts` is a wrapper around the checklist implementation (state and db)
- Takes care of state for the checklists
- Writes to the IndexedDB storage
- Import/Export of checklists
- Large lists can be slow when opening the details within each list (tried using ~2500 in mappct)
   - These only are an issue when opening the list the first time as the items need to be created

**Review by leoetlino — CHANGES_REQUESTED** [review]
partial review, this is too much code for me to review in one pass.

> Reviewed 1 of 19 files at r2, 12 of 20 files at r3, 1 of 8 files at r4, 5 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-:-NZrpE5W07fiZM-r6Ie6:by5sb0s)* status: 19 of 25 files reviewed, 27 unresolved discussions (waiting on @savage13)

___
*[`missing.csv` line 72 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrjhRz3RW6NF1glmbJ:-NZrjhRz3RW6NF1glmbK:badjv68) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/missing.csv#L72)):*
> ```CSV
> Animal_Fish_F, $Item_FishGet_F
> Animal_Fish_G, $Item_FishGet_G
> Animal_Fish_H, $Item_FishGet_H
> ```

rebase; I think this is fixed on master
___
*[`public/icons/badge.svg` line 1 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrjnGL31iAhVoFxROx:-NZrjnGL31iAhVoFxROy:b-cmjrh4) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/public/icons/badge.svg#L1)):*
> ```SVG
> <svg viewBox="-10 -10 120 120" xmlns="http://www.w3.org/2000/svg">
> ```

can we give this file a more descriptive name?
___
*[`src/MapMarker.ts` line 34 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrkR3r1b73KZfQ5-30:-NZrkR3r1b73KZfQ5-31:bjw8j3b) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/MapMarker.ts#L34)):*
> ```XML
>   protected commonInit(): void {
>     this.getMarker().on({ 'click': () => this.mb.emitMarkerSelectedEvent(this) });
>   }
> ```

add a line break below
___
*[`src/MapMarker.ts` line 38 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrkMBd5AnOgTkGOF6A:-NZrkMBd5AnOgTkGOF6B:b-87sths) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/MapMarker.ts#L38)):*
> ```XML
>     const marker = this.getMarker();
>     if (marker instanceof L.CircleMarker) {
>       marker.setStyle({ opacity: opacity, fillOpacity: opacity });
> ```

`opacity,` (don't need to repeat the property name)
___
*[`src/MapMarker.ts` line 50 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrlDX31HQDkuRBqT92:-NZrlDX31HQDkuRBqT93:bgw38e4) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/MapMarker.ts#L50)):*
> ```XML
> }
> 
> function iconAddBadge(icon: L.Icon, anchor: [number, number] | undefined = undefined) {
> ```

should clarify what kind of badge this is
___
*[`src/MapMarker.ts` line 59 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrlBv70fJOeI8x8qEh:-NZrlBv70fJOeI8x8qEi:bjyz9g8) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/MapMarker.ts#L59)):*
> ```XML
> 
> class MapMarkerImpl extends MapMarker {
>   private icons: L.Icon[] = [];
> ```

line break
___
*[`src/MapMarker.ts` line 59 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrlmuy5r9pGycheLFQ:-NZrlmuy5r9pGycheLFR:bwppzao) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/MapMarker.ts#L59)):*
> ```XML
> 
> class MapMarkerImpl extends MapMarker {
>   private icons: L.Icon[] = [];
> ```

should clarify what this array is used for and what the indices are
___
*[`src/MapMarker.ts` line 69 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrl43x3UmVJnOGpbLN:-NZrl43x3UmVJnOGpbLO:b-bbaruy) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/MapMarker.ts#L69)):*
> ```XML
>       contextmenuItems: [
>         {
>           text: 'Toggle Completed',
> ```

"Toggle completed" (I think we generally don't use title case in the other right-click dropdown menus)
___
*[`src/MapMarker.ts` line 83 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrm2Sn3vmUN3UZ6jEA:-NZrm2Sn3vmUN3UZ6jEB:b-4zlw69) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/MapMarker.ts#L83)):*
> ```XML
>   }
> 
>   getLabel() { return ""; }
> ```

getLabel is too vague as a name
___
*[`src/MapMarker.ts` line 540 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrmceT-QmkQp76m0Go:-NZrmceT-QmkQp76m0Gp:b9fkpi2) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/MapMarker.ts#L540)):*
> ```XML
>       className: classToColor(id),
>       // @ts-ignore
>       contextmenuItems: [
> ```

this is duplicated too many times. can we deduplicate this?
___
*[`src/MapMarkerGroup.ts` line 57 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrmma73Xa6iWs2azmV:-NZrmma73Xa6iWs2azmW:btm8wd7) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/MapMarkerGroup.ts#L57)):*
> ```XML
>   }
> 
>   find(func: (marker: MapMarker) => boolean) {
> ```

would suggest calling func "predicate" instead
___
*[`src/components/AppMap.ts` line 78 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrmuq13T0KJ9-rgUDd:-NZrmuq13T0KJ9-rgUDe:btlee08) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMap.ts#L78)):*
> ```XML
> }
> 
> const ALPHAS: { [key: string]: number } = {
> ```

more specific name please?
___
*[`src/components/AppMap.ts` line 321 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrmz3kB-zR4A1O-nzD:-NZrmz3kB-zR4A1O-nzE:b5jcc6v) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMap.ts#L321)):*
> ```XML
>   private areaAutoItem = new ui.Unobservable(L.layerGroup());
> 
>   private skipMarked: boolean = false;
> ```

more specific name please
___
*[`src/components/AppMap.ts` line 322 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrn1oR1RWKg3LqOI75:-NZrn1oR1RWKg3LqOI76:bhil03o) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMap.ts#L322)):*
> ```XML
> 
>   private skipMarked: boolean = false;
>   private checklists: Checklist = new Checklist();
> ```

is this supposed to be one checklist or several? if the former, the name shouldn't be plural
___
*[`src/components/AppMap.ts` line 357 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrn8fF5_h5xk1IRs0z:-NZrn8fF5_h5xk1IRs1-:bbink9s) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMap.ts#L357)):*
> ```XML
>       return true;
>     }
>     if (this.checklists.isMarked(result.hash_id)) { // If found, skip
> ```

comment seems redundant
___
*[`src/components/AppMap.ts` line 465 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrnFB63vpIgkAks9_3:-NZrnFB63vpIgkAks9_4:b-llo3tp) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMap.ts#L465)):*
> ```XML
>         markers.map((m: any) => new (component.cl)(this.map, m, { showLabel: this.showKorokIDs }))
>           .map((marker: any) => {
>             this.updateMarkerCheckmark(marker);
> ```

maps shouldn't have side effects. put this in an actual for loop or a forEach
___
*[`src/components/AppMapChecklistItem.ts` line 11 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrnoK6AVjr5HohCTT2:-NZrnoK73nPP3HyXYcHN:b-pi9d9n) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMapChecklistItem.ts#L11)):*
> ```XML
> @Component({
>   components: {
>     //ObjectInfo,
> ```

remove this
___
*[`src/components/AppMapChecklistItem.ts` line 16 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrnl4fEoaduPezoM4h:-NZrnl4fEoaduPezoM4i:b-lxgz7a) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMapChecklistItem.ts#L16)):*
> ```XML
> export default class AppMapChecklistItem extends Vue {
>   @Prop()
>   private item!: any;
> ```

needs an actual type, not any
___
*[`src/components/AppMapChecklistItem.ts` line 19 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrnmf18qu6uoR30B85:-NZrnmf18qu6uoR30B86:b-7ilvog) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMapChecklistItem.ts#L19)):*
> ```XML
> 
>   @Prop()
>   private bus!: any;
> ```

type?
___
*[`src/components/AppMapChecklistItem.vue` line 6 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrntJB7_a5H7k5Ilho:-NZrntJCAUIpEcg-6TJC:bhufwgr) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMapChecklistItem.vue#L6)):*
> ```Vue
>     <b-btn class="small" size="sm"
>            style="padding-top:0; padding-bottom: 0; font-size: inherit; padding-left: 2px;"
>            variant="link" @click='searchOnValue(`"${item.name}"`)'>{{item.ui_name}}</b-btn>
> ```

`searchOnValue(item.name)`?
___
*[`src/components/AppMapDetailsDungeon.vue` line 6 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZroE3V1r8YjLUaVy-5:-NZroE3V1r8YjLUaVy-6:b2l3xl6) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMapDetailsDungeon.vue#L6)):*
> ```Vue
>     <div>Dungeon number: {{marker.data.dungeonNum}}</div>
>     <div v-if="marker.data.lm.l.ShrineInCave" style="color: orange"><i class="fa fa-exclamation-circle"></i> Inside Cave</div>
>     <section title="Warning: This is the Marker Position; actual Dungeon Position may be different ">Position: {{pos[0].toFixed(2)}}, {{pos[1].toFixed(2)}}, {{(-pos[2]).toFixed(2)}}</section>
> ```

"marker position" etc.
___
*[`src/components/AppMapDetailsObj.ts` line 157 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZroLY-4750b6mOg42g:-NZroLY-4750b6mOg42h:bjyz9g8) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMapDetailsObj.ts#L157)):*
> ```XML
>     this.initKorokMarkers();
>     this.initRails();
>   }
> ```

line break
___
*[`src/components/AppMapDetailsObj.ts` line 159 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZroQLw4Y2O-GV5bnnS:-NZroQLw4Y2O-GV5bnnT:b59n1xc) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMapDetailsObj.ts#L159)):*
> ```XML
>   }
>   mounted() {
>     this.$on('AppMap:update-search-markers', (value: any) => {
> ```

do we really need this? seems a bit odd
___
*[`src/components/ObjectInfo.ts` line 44 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZro_Bu2qI6BccGVWkD:-NZro_Bu2qI6BccGVWkE:b-ghbmz0) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/ObjectInfo.ts#L44)):*
> ```XML
>     this.$parent.$emit('AppMap:update-search-markers', {
>       hash_id: this.data.hash_id,
>       label: "",
> ```

I've seen this several times now -- can we make it so we don't have to pass a useless label: "" in various places?
___
*[`src/components/ObjectInfo.vue` line 17 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrokrn61Se81BYLcsu:-NZrokrn61Se81BYLcsv:b2mfe2l) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/ObjectInfo.vue#L17)):*
> ```Vue
>                                               append>{{formatObjId(data.hash_id)}}</router-link></span>
>       <span v-if="!withPermalink">{{formatObjId(data.hash_id)}}</span>
>       <div style="display: inline; text-shadow: none;" @click.stop.prevent="toggleCheck()" title="Mark as found or not">
> ```

this should be a link or a button, not a div
___
*[`src/util/Checklist.ts` line 30 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrow9vCa3NsEBwVL0R:-NZrow9vCa3NsEBwVL0S:b-39u3sz) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/util/Checklist.ts#L30)):*
> ```XML
>   marked: { [key: string]: boolean };
>   lists: List[];
>   constructor() {
> ```

line breaks please (here and elsewhere)
___
*[`src/util/settings.ts` line 46 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrp4MB3eAiqlWfGd5F:-NZrp4MB3eAiqlWfGd5G:b-g23gef) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/util/settings.ts#L46)):*
> ```XML
>   noTouchScreen!: boolean;
> 
>   checklists!: { [key: string]: any };
> ```

is this still used?

**Review by savage13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldamods/objmap-totk/70)* status: 19 of 25 files reviewed, 27 unresolved discussions (waiting on @leoetlino)

___
*[`missing.csv` line 72 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrjhRz3RW6NF1glmbJ:-NZuowouDqM6VUETNzfw:b-896fix) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/missing.csv#L72)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

rebase; I think this is fixed on master
</blockquote></details>

Done.
___
*[`public/icons/badge.svg` line 1 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrjnGL31iAhVoFxROx:-NZupK3v9ddlJ4WKwlBF:bcljw5f) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/public/icons/badge.svg#L1)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

can we give this file a more descriptive name?
</blockquote></details>

Yep. Changed to checkmark.svg
___
*[`src/MapMarker.ts` line 34 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrkR3r1b73KZfQ5-30:-NZupfdH0lx8123Zf3IU:b-896fix) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/MapMarker.ts#L34)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

add a line break below
</blockquote></details>

Done.
___
*[`src/MapMarker.ts` line 38 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrkMBd5AnOgTkGOF6A:-NZupmTV6VC1Bj8ykYt2:b-896fix) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/MapMarker.ts#L38)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`opacity,` (don't need to repeat the property name)
</blockquote></details>

Done.
___
*[`src/MapMarker.ts` line 50 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrlDX31HQDkuRBqT92:-NZupvw_Ee6o3PMGNDCU:b-qqb42) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/MapMarker.ts#L50)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

should clarify what kind of badge this is
</blockquote></details>

Done. Changed from badge to checkmark
___
*[`src/MapMarker.ts` line 59 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrlBv70fJOeI8x8qEh:-NZuq3LQ2A_tZS1mV4W2:b-896fix) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/MapMarker.ts#L59)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

line break
</blockquote></details>

Done.
___
*[`src/MapMarker.ts` line 59 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrlmuy5r9pGycheLFQ:-NZuql2Y4h8xXIyzZBaV:b-1k16e1) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/MapMarker.ts#L59)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

should clarify what this array is used for and what the indices are
</blockquote></details>

Done. Added a comment regarding the icons variable.
___
*[`src/MapMarker.ts` line 69 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrl43x3UmVJnOGpbLN:-NZur14KDoF6EtLS6sGA:b-896fix) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/MapMarker.ts#L69)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

"Toggle completed" (I think we generally don't use title case in the other right-click dropdown menus)
</blockquote></details>

Done.
___
*[`src/MapMarker.ts` line 83 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrm2Sn3vmUN3UZ6jEA:-NZurQE32L1MD5M87Pdo:b-v5l5gx) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/MapMarker.ts#L83)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

getLabel is too vague as a name
</blockquote></details>

Done. Changed to getMarkerCategory()
___
*[`src/MapMarker.ts` line 540 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrmceT-QmkQp76m0Go:-N_9k-g-94IYc5eRy18O:b-896fix) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/MapMarker.ts#L540)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

this is duplicated too many times. can we deduplicate this?
</blockquote></details>

Done.
___
*[`src/MapMarkerGroup.ts` line 57 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrmma73Xa6iWs2azmV:-NZuryBB9s9O-ocTawT1:b-896fix) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/MapMarkerGroup.ts#L57)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

would suggest calling func "predicate" instead
</blockquote></details>

Done.
___
*[`src/components/AppMap.ts` line 78 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrmuq13T0KJ9-rgUDd:-NZusGU71S4R1RcgI1cf:b-z7mbsp) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMap.ts#L78)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

more specific name please?
</blockquote></details>

Done. Now MARKER_OPACITIES
___
*[`src/components/AppMap.ts` line 321 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrmz3kB-zR4A1O-nzD:-NZusWfo1-0n10QUkDtV:b-e0o9g5) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMap.ts#L321)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

more specific name please
</blockquote></details>

Done. Now skipCompletedObjects
___
*[`src/components/AppMap.ts` line 322 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrn1oR1RWKg3LqOI75:-NZusrA960ophvHm6MeN:b-xi14st) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMap.ts#L322)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

is this supposed to be one checklist or several? if the former, the name shouldn't be plural
</blockquote></details>

Done. Changed the class to Checklists for clarity
___
*[`src/components/AppMap.ts` line 357 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrn8fF5_h5xk1IRs0z:-NZut0_P73sstttiAASN:b-5mw4c9) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMap.ts#L357)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

comment seems redundant
</blockquote></details>

Done. Removed
___
*[`src/components/AppMap.ts` line 465 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrnFB63vpIgkAks9_3:-N_4bn9-3N7zT23C1fk3:bb6un1j) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMap.ts#L465)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

maps shouldn't have side effects. put this in an actual for loop or a forEach
</blockquote></details>

Done
___
*[`src/components/AppMapChecklistItem.ts` line 11 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrnoK6AVjr5HohCTT2:-NZutkROCv2jlo3G5QwL:b-896fix) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMapChecklistItem.ts#L11)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

remove this
</blockquote></details>

Done.
___
*[`src/components/AppMapChecklistItem.ts` line 16 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrnl4fEoaduPezoM4h:-NZuuSDA89dCYIsa9ugm:b-896fix) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMapChecklistItem.ts#L16)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

needs an actual type, not any
</blockquote></details>

Done.
___
*[`src/components/AppMapChecklistItem.ts` line 19 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrnmf18qu6uoR30B85:-NZuuTpW4kX5gs-2y-Kh:b-896fix) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMapChecklistItem.ts#L19)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

type?
</blockquote></details>

Done.
___
*[`src/components/AppMapChecklistItem.vue` line 6 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrntJB7_a5H7k5Ilho:-NZuuzFf102ok28Dqp91:b-896fix) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMapChecklistItem.vue#L6)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`searchOnValue(item.name)`?
</blockquote></details>

Done.
___
*[`src/components/AppMapDetailsDungeon.vue` line 6 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZroE3V1r8YjLUaVy-5:-NZuvCIG2v3TxTxZVNp_:b-896fix) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMapDetailsDungeon.vue#L6)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

"marker position" etc.
</blockquote></details>

Done.
___
*[`src/components/AppMapDetailsObj.ts` line 157 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZroLY-4750b6mOg42g:-NZuvPrmA12Qk0JskLXn:b-896fix) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMapDetailsObj.ts#L157)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

line break
</blockquote></details>

Done.
___
*[`src/components/AppMapDetailsObj.ts` line 159 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZroQLw4Y2O-GV5bnnS:-NZuvWic6bVpSTr4gUeG:b-tfi0ak) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/AppMapDetailsObj.ts#L159)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

do we really need this? seems a bit odd
</blockquote></details>

Done. Vue does not forward messages up the chain.  ObjectInfo is used in AppMap and in AppMapDetailsObj.  Without this the message never gets from ObjectInfo to AppMap if  it needs to go through AppMapDetailsObj. 
___
*[`src/components/ObjectInfo.ts` line 44 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZro_Bu2qI6BccGVWkD:-NZuxo64Axty4F-VnW5b:bb6un1j) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/ObjectInfo.ts#L44)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I've seen this several times now -- can we make it so we don't have to pass a useless label: "" in various places?
</blockquote></details>

Done
___
*[`src/components/ObjectInfo.vue` line 17 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrokrn61Se81BYLcsu:-N_-Xgdu8bC0MuUABqSb:b-896fix) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/components/ObjectInfo.vue#L17)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

this should be a link or a button, not a div
</blockquote></details>

Done.
___
*[`src/util/Checklist.ts` line 30 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrow9vCa3NsEBwVL0R:-NZuwciN61667RJag9Kl:b-896fix) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/util/Checklist.ts#L30)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

line breaks please (here and elsewhere)
</blockquote></details>

Done.
___
*[`src/util/settings.ts` line 46 at r5](https://reviewable.io/reviews/zeldamods/objmap-totk/70#-NZrp4MB3eAiqlWfGd5F:-NZuwlMf0GnI8Jt6_vYQ:b-mytsmx) ([raw file](https://github.com/zeldamods/objmap-totk/blob/e3001b082560a8ec73e624531917d3b578bec3f9/src/util/settings.ts#L46)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

is this still used?
</blockquote></details>

Done. Removed, it is not used anymore.

**Comment by savage13** [comment]
I have not rebased the PR, but it appears to be able to merge without conflict.

Sorry the PR is so big. It seems to touch almost everything in the codebase.

**Pull request merged**
